[package]
name = "password_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
rpassword = "7.0"
aes = "0.7"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
config = "0.14.0"